apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Release.Name }}-web'
spec:
  rules:
  - host: '{{ .Values.web.ingress.hostname }}'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: '{{ .Release.Name }}-web'
            port:
              name: web
  {{- if .Values.web.ingress.tls.enabled }}
  tls:
  - hosts:
    - '{{ .Values.web.ingress.hostname }}'
    secretName: {{ .Release.Name }}-cert
  {{- end }}